// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovoApiBarbearia.Data;

namespace NovoApiBarbearia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220426041319_Adicioado uma parte da controller Fucionarios")]
    partial class AdicioadoumapartedacontrollerFucionarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("NovoApiBarbearia.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Jhonny",
                            Telefone = "69992939145"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Roberto",
                            Telefone = "69125125"
                        });
                });

            modelBuilder.Entity("NovoApiBarbearia.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "1",
                            Nome = "Thiaho",
                            Senha = "123"
                        });
                });

            modelBuilder.Entity("NovoApiBarbearia.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Corte",
                            Valor = 25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
